import { extractEventMaps} from '@lickle/dom/build'
import fs from 'fs'

const eventMaps = extractEventMaps()

const Overloads = `
// This file is generated by build.js
import { Observable } from './observable.js'

/**
 * Creates an observable from DOM events.
 *
 * @param target The event target (Element, Document, Window, etc)
 * @param eventName The name of the event to listen for
 * @param options Optional event listener options
 * @return Observable that emits events when they occur
 */
export const fromEvent: FromEvent = (target: any, eventName: any, options?: any) => {
  return (observer: any) => {
    const handler = (e: any) => observer.next(e)
    target.addEventListener(eventName, handler, options)
    return () => target.removeEventListener(eventName, handler, options)
  }
}

/**
 * Type overloads for dom event emitters.
 * Generated from the lib.dom.d.ts file.
 */
export interface FromEvent {
  ${eventMaps.map(({ map, targets }) => `<K extends keyof ${map}>(
    target: ${targets.join(' | ')},
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<${map}[K]>`).join('\n')}
}
`

fs.writeFileSync('src/browser.ts', Overloads.trim())