/**
 * Browser-specific observables for DOM events, fetch, and other Web APIs.
 * @module
 */

// This file is generated by build.js
import { Observable } from './observable.js'

/**
 * Creates an observable from DOM events.
 *
 * @param target The event target (Element, Document, Window, etc)
 * @param eventName The name of the event to listen for
 * @param options Optional event listener options
 * @return Observable that emits events when they occur
 */
export const fromDomEvent: FromDom = (target: any, eventName: any, options?: any) => {
  return (observer: any) => {
    const handler = (e: any) => observer.next(e)
    target.addEventListener(eventName, handler, options)
    return () => target.removeEventListener(eventName, handler, options)
  }
}

/**
 * Type overloads for dom event emitters.
 * Generated from the lib.dom.d.ts file.
 */
export interface FromDom {
  <K extends keyof AbortSignalEventMap>(
    target: AbortSignal,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<AbortSignalEventMap[K]>
  <K extends keyof AnimationEventMap>(
    target: Animation | CSSAnimation | CSSTransition,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<AnimationEventMap[K]>
  <K extends keyof AudioScheduledSourceNodeEventMap>(
    target: AudioBufferSourceNode | AudioScheduledSourceNode | ConstantSourceNode | OscillatorNode,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<AudioScheduledSourceNodeEventMap[K]>
  <K extends keyof BaseAudioContextEventMap>(
    target: AudioContext | BaseAudioContext,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<BaseAudioContextEventMap[K]>
  <K extends keyof AudioDecoderEventMap>(
    target: AudioDecoder,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<AudioDecoderEventMap[K]>
  <K extends keyof AudioEncoderEventMap>(
    target: AudioEncoder,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<AudioEncoderEventMap[K]>
  <K extends keyof AudioWorkletNodeEventMap>(
    target: AudioWorkletNode,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<AudioWorkletNodeEventMap[K]>
  <K extends keyof BroadcastChannelEventMap>(
    target: BroadcastChannel,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<BroadcastChannelEventMap[K]>
  <K extends keyof MediaStreamTrackEventMap>(
    target: CanvasCaptureMediaStreamTrack | MediaStreamTrack,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<MediaStreamTrackEventMap[K]>
  <K extends keyof CookieStoreEventMap>(
    target: CookieStore,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<CookieStoreEventMap[K]>
  <K extends keyof DocumentEventMap>(
    target: Document | HTMLDocument | XMLDocument,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<DocumentEventMap[K]>
  <K extends keyof EventSourceEventMap>(
    target: EventSource,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<EventSourceEventMap[K]>
  <K extends keyof FileReaderEventMap>(
    target: FileReader,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<FileReaderEventMap[K]>
  <K extends keyof FontFaceSetEventMap>(
    target: FontFaceSet,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<FontFaceSetEventMap[K]>
  <K extends keyof HTMLElementEventMap>(
    target: HTMLElement,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<HTMLElementEventMap[K]>
  <K extends keyof HTMLMediaElementEventMap>(
    target: HTMLAudioElement | HTMLMediaElement,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<HTMLMediaElementEventMap[K]>
  <K extends keyof HTMLBodyElementEventMap>(
    target: HTMLBodyElement,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<HTMLBodyElementEventMap[K]>
  <K extends keyof HTMLFrameSetElementEventMap>(
    target: HTMLFrameSetElement,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<HTMLFrameSetElementEventMap[K]>
  <K extends keyof HTMLVideoElementEventMap>(
    target: HTMLVideoElement,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<HTMLVideoElementEventMap[K]>
  <K extends keyof IDBDatabaseEventMap>(
    target: IDBDatabase,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<IDBDatabaseEventMap[K]>
  <K extends keyof IDBOpenDBRequestEventMap>(
    target: IDBOpenDBRequest,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<IDBOpenDBRequestEventMap[K]>
  <K extends keyof IDBRequestEventMap>(
    target: IDBRequest<any>,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<IDBRequestEventMap[K]>
  <K extends keyof IDBTransactionEventMap>(
    target: IDBTransaction,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<IDBTransactionEventMap[K]>
  <K extends keyof MIDIAccessEventMap>(
    target: MIDIAccess,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<MIDIAccessEventMap[K]>
  <K extends keyof MIDIInputEventMap>(
    target: MIDIInput,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<MIDIInputEventMap[K]>
  <K extends keyof MIDIPortEventMap>(
    target: MIDIOutput | MIDIPort,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<MIDIPortEventMap[K]>
  <K extends keyof MathMLElementEventMap>(
    target: MathMLElement,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<MathMLElementEventMap[K]>
  <K extends keyof MediaDevicesEventMap>(
    target: MediaDevices,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<MediaDevicesEventMap[K]>
  <K extends keyof MediaKeySessionEventMap>(
    target: MediaKeySession,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<MediaKeySessionEventMap[K]>
  <K extends keyof MediaQueryListEventMap>(
    target: MediaQueryList,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<MediaQueryListEventMap[K]>
  <K extends keyof MediaRecorderEventMap>(
    target: MediaRecorder,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<MediaRecorderEventMap[K]>
  <K extends keyof MediaSourceEventMap>(
    target: MediaSource,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<MediaSourceEventMap[K]>
  <K extends keyof MediaStreamEventMap>(
    target: MediaStream,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<MediaStreamEventMap[K]>
  <K extends keyof MessagePortEventMap>(
    target: MessagePort,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<MessagePortEventMap[K]>
  <K extends keyof NavigationHistoryEntryEventMap>(
    target: NavigationHistoryEntry,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<NavigationHistoryEntryEventMap[K]>
  <K extends keyof NotificationEventMap>(
    target: Notification,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<NotificationEventMap[K]>
  <K extends keyof OfflineAudioContextEventMap>(
    target: OfflineAudioContext,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<OfflineAudioContextEventMap[K]>
  <K extends keyof OffscreenCanvasEventMap>(
    target: OffscreenCanvas,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<OffscreenCanvasEventMap[K]>
  <K extends keyof PaymentRequestEventMap>(
    target: PaymentRequest,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<PaymentRequestEventMap[K]>
  <K extends keyof PaymentResponseEventMap>(
    target: PaymentResponse,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<PaymentResponseEventMap[K]>
  <K extends keyof PerformanceEventMap>(
    target: Performance,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<PerformanceEventMap[K]>
  <K extends keyof PermissionStatusEventMap>(
    target: PermissionStatus,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<PermissionStatusEventMap[K]>
  <K extends keyof PictureInPictureWindowEventMap>(
    target: PictureInPictureWindow,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<PictureInPictureWindowEventMap[K]>
  <K extends keyof RTCDTMFSenderEventMap>(
    target: RTCDTMFSender,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<RTCDTMFSenderEventMap[K]>
  <K extends keyof RTCDataChannelEventMap>(
    target: RTCDataChannel,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<RTCDataChannelEventMap[K]>
  <K extends keyof RTCDtlsTransportEventMap>(
    target: RTCDtlsTransport,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<RTCDtlsTransportEventMap[K]>
  <K extends keyof RTCIceTransportEventMap>(
    target: RTCIceTransport,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<RTCIceTransportEventMap[K]>
  <K extends keyof RTCPeerConnectionEventMap>(
    target: RTCPeerConnection,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<RTCPeerConnectionEventMap[K]>
  <K extends keyof RTCSctpTransportEventMap>(
    target: RTCSctpTransport,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<RTCSctpTransportEventMap[K]>
  <K extends keyof RemotePlaybackEventMap>(
    target: RemotePlayback,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<RemotePlaybackEventMap[K]>
  <K extends keyof SVGElementEventMap>(
    target: SVGElement,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<SVGElementEventMap[K]>
  <K extends keyof SVGSVGElementEventMap>(
    target: SVGSVGElement,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<SVGSVGElementEventMap[K]>
  <K extends keyof ScreenOrientationEventMap>(
    target: ScreenOrientation,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<ScreenOrientationEventMap[K]>
  <K extends keyof ScriptProcessorNodeEventMap>(
    target: ScriptProcessorNode,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<ScriptProcessorNodeEventMap[K]>
  <K extends keyof ServiceWorkerEventMap>(
    target: ServiceWorker,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<ServiceWorkerEventMap[K]>
  <K extends keyof ServiceWorkerContainerEventMap>(
    target: ServiceWorkerContainer,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<ServiceWorkerContainerEventMap[K]>
  <K extends keyof ServiceWorkerRegistrationEventMap>(
    target: ServiceWorkerRegistration,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<ServiceWorkerRegistrationEventMap[K]>
  <K extends keyof ShadowRootEventMap>(
    target: ShadowRoot,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<ShadowRootEventMap[K]>
  <K extends keyof SourceBufferEventMap>(
    target: SourceBuffer,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<SourceBufferEventMap[K]>
  <K extends keyof SourceBufferListEventMap>(
    target: SourceBufferList,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<SourceBufferListEventMap[K]>
  <K extends keyof SpeechSynthesisEventMap>(
    target: SpeechSynthesis,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<SpeechSynthesisEventMap[K]>
  <K extends keyof SpeechSynthesisUtteranceEventMap>(
    target: SpeechSynthesisUtterance,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<SpeechSynthesisUtteranceEventMap[K]>
  <K extends keyof TextTrackEventMap>(
    target: TextTrack,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<TextTrackEventMap[K]>
  <K extends keyof TextTrackCueEventMap>(
    target: TextTrackCue | VTTCue,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<TextTrackCueEventMap[K]>
  <K extends keyof TextTrackListEventMap>(
    target: TextTrackList,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<TextTrackListEventMap[K]>
  <K extends keyof VideoDecoderEventMap>(
    target: VideoDecoder,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<VideoDecoderEventMap[K]>
  <K extends keyof VideoEncoderEventMap>(
    target: VideoEncoder,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<VideoEncoderEventMap[K]>
  <K extends keyof VisualViewportEventMap>(
    target: VisualViewport,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<VisualViewportEventMap[K]>
  <K extends keyof WakeLockSentinelEventMap>(
    target: WakeLockSentinel,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<WakeLockSentinelEventMap[K]>
  <K extends keyof WebSocketEventMap>(
    target: WebSocket,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<WebSocketEventMap[K]>
  <K extends keyof WindowEventMap>(
    target: Window,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<WindowEventMap[K]>
  <K extends keyof WindowEventHandlersEventMap>(
    target: WindowEventHandlers,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<WindowEventHandlersEventMap[K]>
  <K extends keyof WorkerEventMap>(
    target: Worker,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<WorkerEventMap[K]>
  <K extends keyof XMLHttpRequestEventMap>(
    target: XMLHttpRequest,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<XMLHttpRequestEventMap[K]>
  <K extends keyof XMLHttpRequestEventTargetEventMap>(
    target: XMLHttpRequestEventTarget | XMLHttpRequestUpload,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<XMLHttpRequestEventTargetEventMap[K]>
  <K extends keyof ElementEventMap>(
    target: Element,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<ElementEventMap[K]>
  <K extends keyof GlobalEventHandlersEventMap>(
    target: GlobalEventHandlers,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<GlobalEventHandlersEventMap[K]>
  <K extends keyof AbstractWorkerEventMap>(
    target: AbstractWorker | SharedWorker,
    eventName: K,
    options?: boolean | AddEventListenerOptions,
  ): Observable<AbstractWorkerEventMap[K]>
}
